In [8]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]


In [9]:
print(a1.max())

6


In [10]:
print(a1.min())

1


In [11]:
print(type(a1))

<class 'numpy.ndarray'>


In [12]:
print(a1[0])

1


In [13]:
print(a1[2])

3


In [15]:
print(a1[-1])

6


In [17]:
print(a1[-3])

4


In [18]:
print(a1[1:3])

[2 3]


In [19]:
print(a1[0:5])

[1 2 3 4 5]


In [20]:
print(a1[:4])

[1 2 3 4]


In [21]:
print(a1[::2])

[1 3 5]


In [22]:
print(a1[3:])

[4 5 6]


In [24]:
print(a1[2::])

[3 4 5 6]


In [25]:
print(a1[-3-1])

3


In [5]:
import numpy as np
a2=np.array([1,2,3,4,5,6,6,8])
x=a2.copy()
a2[0]=42
print(a2)
print(x)

[42  2  3  4  5  6  6  8]
[1 2 3 4 5 6 6 8]


In [7]:
import numpy as np
a3=np.array([[1,2,3,4],[5,6,7,8]])
print(a3.shape)

(2, 4)


In [8]:
print(a3.shape)

(2, 4)


In [17]:
import numpy as np
a4=np.array([1,2,3,4,5,6])
newarray=a4.reshape(3,2)
print(newarray)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
import numpy as np
a5=np.array([1,2,3,4])
for x in a5:
    print(x)

1
2
3
4


In [23]:
import numpy as np
a6=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for x in a6:
    print(x)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [29]:
import numpy as np
a7=np.array([1,2,3,4,5])
a8=np.array([6,7,8,9,10])
arr=np.concatenate((a7, a8))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
import numpy as np
a9=np.array([1,2,3,4,5,6])
newarr=np.array_split(a9,2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [45]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4,7,3])
x=np.where(arr==4)
print(x)

(array([3, 6], dtype=int64),)


In [46]:
print(np.sort(arr))

[1 2 3 3 4 4 5 6 7]
