In [8]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]


In [9]:
print(a1.max())

6


In [10]:
print(a1.min())

1


In [11]:
print(type(a1))

<class 'numpy.ndarray'>


In [12]:
print(a1[0])

1


In [13]:
print(a1[2])

3


In [15]:
print(a1[-1])

6


In [17]:
print(a1[-3])

4


In [18]:
print(a1[1:3])

[2 3]


In [19]:
print(a1[0:5])

[1 2 3 4 5]


In [20]:
print(a1[:4])

[1 2 3 4]


In [21]:
print(a1[::2])

[1 3 5]


In [22]:
print(a1[3:])

[4 5 6]


In [24]:
print(a1[2::])

[3 4 5 6]


In [25]:
print(a1[-3-1])

3


In [5]:
import numpy as np
a2=np.array([1,2,3,4,5,6,6,8])
x=a2.copy()
a2[0]=42
print(a2)
print(x)

[42  2  3  4  5  6  6  8]
[1 2 3 4 5 6 6 8]


In [7]:
import numpy as np
a3=np.array([[1,2,3,4],[5,6,7,8]])
print(a3.shape)

(2, 4)


In [8]:
print(a3.shape)

(2, 4)


In [17]:
import numpy as np
a4=np.array([1,2,3,4,5,6])
newarray=a4.reshape(3,2)
print(newarray)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
import numpy as np
a5=np.array([1,2,3,4])
for x in a5:
    print(x)

1
2
3
4


In [23]:
import numpy as np
a6=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for x in a6:
    print(x)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [29]:
import numpy as np
a7=np.array([1,2,3,4,5])
a8=np.array([6,7,8,9,10])
arr=np.concatenate((a7, a8))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
import numpy as np
a9=np.array([1,2,3,4,5,6])
newarr=np.array_split(a9,2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [45]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4,7,3])
x=np.where(arr==4)
print(x)

(array([3, 6], dtype=int64),)


In [46]:
print(np.sort(arr))

[1 2 3 3 4 4 5 6 7]


# practice purpose

In [4]:
import numpy as np
a=np.array([2,3,4,9,5,6,1])
print(a)

[2 3 4 9 5 6 1]


In [5]:
import numpy as np
a=[2,3,4,9,5,6,1]
print(a)

[2, 3, 4, 9, 5, 6, 1]


In [6]:
print(np.__version__)

1.20.3


In [9]:
import numpy as np
arr=np.array([3,2,5,4,6])
print(arr)
print(type(arr))

[3 2 5 4 6]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr=np.array((3,2,5,4,6))
print(arr)

[3 2 5 4 6]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [81]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[9,8,7]]])
print(arr.shape)

(2, 2, 3)


In [21]:
import numpy as np
a=np.array(12)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[5,7,8]])
d=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,8,7]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [27]:
import numpy as np
arr=np.array([[17,4,32,2],[3,4,5,6,7]])
print(arr[0])

[17, 4, 32, 2]


C:\Users\Ammani\AppData\Local\Temp/ipykernel_5308/2454887251.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[17,4,32,2],[3,4,5,6,7]])


In [24]:
print(arr[2]+arr[0])

49


In [29]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 4])

10


In [34]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,-3])

1


In [15]:
import numpy as np
arr=np.array([1,2,3,4,4,7])
arr.reshape(2,3)
print(arr)

[1 2 3 4 4 7]


In [38]:
print(arr[:3])

[1 2 3]


In [44]:
print(arr[::5])

[1 8]


In [47]:
print(arr[1::])

[2 3 9 5 8]


In [50]:
print(arr[1:4:2])

[2 9]


In [52]:
print(arr[0:4:3])

[1 9]


In [53]:
print(arr.dtype)

int32


In [63]:
import numpy as np
arr=np.array([1.2,3.3])
newarr=arr.astype('i')
print(newarr)

[1 3]


In [64]:
arr=np.array([1,2,3,4])
newarr=arr.astype('f')
print(newarr)

[1. 2. 3. 4.]


In [66]:
arr=np.array([1,2,3,4,0])
newarr=arr.astype('bool')
print(newarr)

[ True  True  True  True False]


In [71]:
import numpy as np
arr=np.array([2,3,8,4,6])
x=arr.copy()
arr[2]=100
print(arr)
print(x)

[  2   3 100   4   6]
[2 3 8 4 6]


In [72]:
import numpy as np
arr=np.array([2,3,8,4,6])
x=arr.view()
arr[2]=100
print(arr)
print(x)

[  2   3 100   4   6]
[  2   3 100   4   6]


In [75]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [78]:
import numpy as np
arr=np.array([1,2,3])
print(arr.shape)

(3,)


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
arr=np.concatenate((x,y))
print(arr)

[1 2 3 4 5 6]


In [24]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2]), array([3, 4])]


In [26]:
import numpy as np
arr=np.array([2,3,4,5,2,3,3])
x=np.where(arr==3)
print(x)

(array([1, 5, 6], dtype=int64),)


In [28]:
import numpy as np
arr=np.array([2,3,4,5,2,3,3])
x=np.searchsorted(arr,5)
print(x)

3


In [32]:
import numpy as np
arr=np.array([2,3,4,5,2,3,3])
print(np.sort(arr))

[2 2 3 3 3 4 5]


In [33]:
import numpy as np
arr=np.array([2,3,4,5,2,3,3])
print(np.max(arr))

5


In [34]:
print(arr.min())

2


In [35]:
print(arr.sum())

22


In [36]:
print(arr.mean())

3.142857142857143


In [39]:
print(arr.std())

0.989743318610787


In [40]:
print(arr.var())

0.9795918367346939
